version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: .docker-dev/Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - '.docker-dev/.env'
    command: puma -e development
