version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: .docker-dev/Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:4567"
    env_file:
      - '.docker-dev/.env'
      - '.docker-dev/.env.secret'
    command: rerun --background app.rb
